### ISSUE TITLE
No results from dmoz_cat() call for domain where dmoz.com data exists.

### ISSUE THREAD

**Issue by bwmoore22** [soodoku/domain_classifier#3]
All or at least one of the queries below should return a valid category for the www.crazyguyonabike.com domain. I've used the get_dmoz_data() command and the domain is present in the downloaded file, as well as the dmoz.com web site.

> dmoz_cat(domains="http://www.crazyguyonabike.com")
>           domain_name dmoz_category
> 1 crazyguyonabike.com          <NA>
> dmoz_cat(domains="https://www.crazyguyonabike.com")
>                       domain_name dmoz_category
> 1 https://www.crazyguyonabike.com          <NA>
> dmoz_cat(domains="www.crazyguyonabike.com")
>           domain_name dmoz_category
> 1 crazyguyonabike.com          <NA>
> dmoz_cat(domains="crazyguyonabike.com")
>           domain_name dmoz_category
> 1 crazyguyonabike.com          <NA>

**Comment by soodoku** [comment]
One of the fixes issued via https://github.com/soodoku/domain_classifier/commit/9c0110dd3ad07bb6768bdfd05babe2c23ac83063#diff-3e170c764d9348adeb8a5e2bb1e3f249

So now it works but the function and data still need to be parsed slightly differently.
