### ISSUE TITLE
virustotal_cat() returns different structures depending upon results from virustotal.com

### ISSUE THREAD

**Issue by bwmoore22** [soodoku/domain_classifier#4]
Calls to virustotal_cat() return different structures depending upon what information is available for the domain on virustotal.com. The difference in structure makes programming more difficult when combining information from multiple domains. A better approach would be to return the same structure with NA for missing information.

```
virustotal_cat("www.google.com",apikey = virusTotalApiKey);
domain bitdefender dr_web alexa google websense trendmicro
1 www.google.com searchengines chats google searchengines advertisements search engines portals
virustotal_cat("www.social-buttons.com",apikey = virusTotalApiKey);
domain bitdefender dr_web
1 www.social-buttons.com newly registered websites newly registered websites
Warning message:
In names(d_res)[names(d_res) %in% cat_names] <- c("bitdefender", :
number of items to replace is not a multiple of replacement length
```

**Comment by soodoku** [comment]
Example: 

`virustotal_cat("www.social-buttons.com")
`
                  domain bitdefender                  websense                    google dr_web trendmicro alexa
1 www.social-buttons.com          NA newly registered websites newly registered websites     NA         NA    NA
