### ISSUE TITLE
In virustotal_cat() invalid domain causes call to throw an error on dataframe 

### ISSUE THREAD

**Issue by bwmoore22** [soodoku/domain_classifier#7]
When you pass an invalid domain, virustotal_cat() throws an error with no information about the problem or the data that caused the problem.  The error causes an exit from any current function. The behavior should probably be to issue a warning or message that the domain was not found and return a normal structure with NA for the various entries.

> virustotal_cat("53275950.videos-for-your-business.com",apikey=virusTotalApiKey)
> Error in data.frame(domain, d_res) : 
>   arguments imply differing number of rows: 1, 0
> virustotal_cat("videos-for-your-business.com",apikey=virusTotalApiKey)
>                         domain   bitdefender        dr_web
> 1 videos-for-your-business.com uncategorized uncategorized
> Warning message:
> In names(d_res)[names(d_res) %in% cat_names] <- c("bitdefender",  :
>   number of items to replace is not a multiple of replacement length

**Comment by soodoku** [comment]
Fixed the bug via: https://github.com/soodoku/domain_classifier/commit/2b8165ef1cec3323365e5334184319f918c433f8#diff-3e170c764d9348adeb8a5e2bb1e3f249

virustotal_cat("dfifji.com")
      domain bitdefender dr_web alexa google websense trendmicro
1 dfifji.com          NA     NA    NA     NA       NA         NA
